# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    app.user_voter:
        class: AppBundle\Security\UserVoter
        tags:
            - { name: security.voter }
        # small performance boost
        public: false
    
    # security.authentication.manager:
    #     class: AppBundle\Security\LoginFormAuthenticator
    #     tags:
    #         - { name: security.authentication.manager }

#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
